### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by ghost**
@Willem3141 It's that time of the month again. :smiley:
- [x] Banner
- [x] Page 0 (title)
#### Page 1 (leaving)
- [x] translation
- [x] layout
#### Page 2 (falling)
- [x] translation
- [x] layout
#### Page 3 (encountering)
- [x] translation
- [x] layout
#### Page 4 (scaring)
- [x] translation
- [x] layout
#### Page 5 (eating)
- [x] translation
- [x] layout
#### Page 6 (arriving)
- [x] translation
- [x] layout
#### Page 7 (realizing)
- [x] translation
- [x] layout 
#### Page 8 (patrons)
- [x] translation
- [x] layout

_Een nieuwe start_ may seem a bit cliché? @RJQuiralta said on IRC that he's using _Let's start over_ in the es-MX translation.

I'm writing in English here so Quiralta doesn't think I'm gossiping about him. :wink:

### CODE REVIEW

**Comment by Willem3141** [comment]
Hi! Are you working on translating the pages now? I'd like to help, but let's avoid double work :smile:

**Comment by ghost** [comment]
I wasn't right now. Maybe we can set something up to work together in real-time?

**Comment by ghost** [comment]
I'm trying something new: https://mensuel.framapad.org/p/peppercarrot-ep17-dutch :p

**Comment by ghost** [comment]
We still have to decide on:

**...et voilà. Tu connais à présent toute l'histoire.**
- … en zo ben ik hier toch beland.
- … en zo ben ik hier [toch] veilig en wel geraakt. [nl-BE?]
- … en zo ben ik hier [toch] geraakt. [nl-BE?]
- …

**Comment by Willem3141** [comment]
Using 'geraakt' indeed sounds like nl-BE to me...

Maybe with 'aankomen', like '... en zo ben ik hier uiteindelijk toch aangekomen'.

**Comment by ghost** [comment]
_… en zo ben ik hier uiteindelijk toch aangekomen_ is quite good. I was thinking that I'd like to emphasize a bit more the fact that she has managed to arrive despite the difficulties, just like _geraakt_ conveys. Because _aangekomen_ demands an emphasis, the _uiteindelijk toch_ gets a bit overshadowed. A new thought that just occurred to me: adding a _levend en wel_ or _heelhuids_. _Levend en wel_ is not in the Van Dale, is it common in NL?
↓
- … en zo ben ik hier toch levend en wel aangekomen. [Hmm, on second thought, this doesn't sound that well anyway.]
- … en zo ben ik hier toch heelhuids aangekomen.

Another branch of phrases:
- … en daarom ben ik naar jou gekomen.
- … en dat is waarom ik naar jou ben gekomen.

**Comment by ghost** [comment]
Design by committee level: individual words. :D

**Comment by Willem3141** [comment]
_Heelhuids_ is often used in NL, _levend en wel_ sounds less common (but would not be regarded as strange). I think _… en zo ben ik hier uiteindelijk toch heelhuids aangekomen_ would be a very good option.

We could even do _... en zo heb ik het er uiteindelijk toch heelhuids vanaf gebracht_ but sounds slightly too dramatic to me.

I think _… en daarom ben ik naar jou gekomen_ also doesn't really convey the ‘despite the difficulties’ sense that we're looking for.

> Design by committee level: individual words. :D

Heh :stuck_out_tongue:

**Comment by ghost** [comment]
> We could even do ... en zo heb ik het er uiteindelijk toch heelhuids vanaf gebracht but sounds slightly too dramatic to me.

+1

Actually, +1 to your whole comment ...

**Comment by ghost** [comment]
I'm starting the layout from page 1. If you want, you can start at the end?

**Comment by Willem3141** [comment]
> I'm starting the layout from page 1. If you want, you can start at the end?

Okay, I'll do that.

**Comment by Willem3141** [comment]
I finished page 5 to page 8.

**Comment by ghost** [comment]
Okay, I finished pages 1 to 4. Something I'm changing in the text:
- Ik had natuurlijk liever een paar goede ~~aanvallen~~ **aanvalsspreuken** geleerd, maar goed …

(David cleared that up in the original FR)

**Comment by ghost** [comment]
Ready to merge.

**Comment by Willem3141** [comment]
Perfect! :smile:

**Pull request merged**
